# Generated by Django 5.2.17 on 2026-09-11 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chores', '0002_chore'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chore',
            name='recurrence_day',
            field=models.IntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')], default=0),
        ),
    ]
