# Generated by Django 5.2.17 on 2026-09-11 22:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chores', '0003_alter_chore_recurrence_day'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChoreAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('due_date', models.DateField()),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('COMPLETED', 'Completed'), ('PENALIZED', 'Penalized')], default='PENDING', max_length=10)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('assigned_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chores.roommate')),
                ('chore', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chores.chore')),
            ],
        ),
    ]
